/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://wxd55hhkczf5rpdv3enkic3leq.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5v2ry3nfsjfbhpvrinm5zglghu",
    "aws_cognito_identity_pool_id": "eu-west-1:e4db7455-34fa-4aa8-bbc3-9f475b0e9af3",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "us-east-1_wZP5yzO91",
    "aws_user_pools_web_client_id": "7he7vkierveivn3h265cgk29it",
    "oauth": {}
};

export default awsmobile;
